base/urls.py
from django.contrib import admin
from django.urls import path
from base.views import index

app_name = 'base'

urlpatterns = [
    path('', index, name='home'),
]

duelbola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('forum/', include('forum.urls')),
    path('team/', include('team.urls')),
    path('login/', include('user.urls')),
]

forum/urls.py
from django.contrib import admin
from django.urls import path
from forum.views import index, post, get_data_json

app_name = 'forum'

urlpatterns = [
    path('', index, name="forum"),
    path('post/', post, name="post"),
    path('json/', get_data_json, name="json"),
]

forum/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    user = models.CharField(max_length = 50)
    kategori = models.CharField(max_length = 15)
    post = models.TextField(max_length = 300)
    time_created = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.user +" "+ str(self.time_created)

forum/forms.py
from django import forms
from forum.models import Post

class PostForm(forms.ModelForm):
    kategori = forms.CharField(widget=forms.TextInput(
        attrs = {
            'type' : 'text'
                }
    ))
    post = forms.CharField(widget=forms.Textarea(
        attrs = {
            'type' : 'text'
                }
    ))

    class Meta:
        model = Post
        fields = "__all__"
        exclude = (
            "time_created",
            "user",
        )

forum/views.py
from django.shortcuts import render, redirect
from forum.forms import PostForm
from forum.models import Post
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

def index(request):
    return render(request, 'forum/forum.html')

@login_required(login_url='/login/')
def post(request):
    form = PostForm(request.POST or None)
    context = {
        'form' : form,
    }
    if request.method == "POST":
        if form.is_valid():
            data = request.POST.copy()
            form = PostForm(data)
            saved = form.save()
            saved.user = request.user.username
            saved.save()
            return redirect("forum:forum")
    return render(request, 'forum/post_forum.html', context)

def get_data_json(request):
    data = Post.objects.all()
    data_lst = []
    for i in data:
        dta = i.__dict__.copy()
        del dta["_state"]
        datetime = dta['time_created']
        date = datetime.date()
        time = str(datetime.time())[:8]
        dta['date'] = date
        dta['time'] = time
        data_lst.append(dta)
    return JsonResponse(data_lst,safe=False)
    

forum/templates/forum/forum.html
{% extends 'base/base.html' %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'forum/css/style.css' %}">
    <script src="{% static 'forum/js/script.js' %}"></script>
{% endblock style %}

{% block title %}
    <title>DUEL Forum</title>
{% endblock title %}


{% block body %}
    <div class="home-forum">
        <div class="text-center">
            
            <span><h2>Forum Bersama</h2></span>
            {% if user.is_authenticated %}
               <div id="welcome-user">Welcome {{user.username}} <br></div>
            {% endif %}
            <span>Buat post baru <a href="{% url 'forum:post' %}">di sini</a></span>
        </div>
        <div id="post-forum">
        </div>
    </div>
{% endblock body %}
    
    

forum/templates/forum/post_forum.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}
    
{% block title %}
    <title>DUEL Post Forum</title>
{% endblock title %}


{% block body %}
    <div class="text-center home-forum">
        <h4>
            Apa yang sedang anda pikirkan?
        </h4>
        <div>
            <form action="" method ="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-outline-dark">Buat Post</button>
            </form>
        </div>
    </div>
{% endblock body %}
    
    