base/urls.py
from django.contrib import admin
from django.urls import path
from base.views import index

app_name = 'base'

urlpatterns = [
    path('', index, name='home'),
]

duelbola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('forum/', include('forum.urls')),
    path('team/', include('team.urls')),
    path('login/', include('user.urls')),
]

forum/urls.py
from django.contrib import admin
from django.urls import path
from forum.views import index, post, get_data_json

app_name = 'forum'

urlpatterns = [
    path('', index, name="forum"),
    path('post/', post, name="post"),
    path('json/', get_data_json, name="json"),
]

rekomendasi/urls.py
from django.urls import path
from . import views

app_name = 'rekomendasi'

urlpatterns = [
    path('', views.LocationView.as_view(), name='rekomendasi'),
    # dilanjutkan ...
]

team/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.team, name="team"),
    path('feedback/', views.get_Feedback, name="get_Feedback")
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    ]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def index(request):
    context = {
        'greeting' : 'Welcome To Our Website',

    }

    if request.user.is_authenticated:
        context['greeting'] = 'Welcome ' + request.session["username"]

    return render(request, 'home.html', context)

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width =device-width">

    {% block title %}
      <!-- Pasang title di sini -->
    {% endblock title %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    {% block style %}
        <!-- Pasang style di sini -->
    {% endblock style %}

  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-md navbar-dark my-nav">

        <a class="navbar-brand" href="{% url 'base:home' %}">Duel Website Page</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class= "navbar-nav ml-auto">
                <li class= "nav-item" >
                <a href="{% url 'base:home' %}" class = "nav-link">Home</a>
                </li>
                <li class= "nav-item" >
                <a href="{% url 'rekomendasi:rekomendasi' %}" class = "nav-link">Recommendation</a>
                </li>
                <li class= "nav-item" >
                <a href="{% url 'forum:forum' %}" class = "nav-link">Forum</a>
                </li>
                <li class= "nav-item" >
                <a href="#" class = "nav-link">FAQ</a>
                </li>
                <li class= "nav-item" >
                <a href="{% url 'team:team' %}" class = "nav-link">Our Team</a>
                </li>
                {% if user.is_authenticated %}
                <li class= "nav-item" >
                <a href="{% url 'user:logout' %}" class = "nav-link" id="logout">Logout</a>
                </li>
                {% else %}
                <li class= "nav-item" >
                <a href="{% url 'user:login' %}" class = "nav-link">Login</a>
                </li>
                {% endif %}
           </ul>
        </div>
    </nav>

    {% block body %}
        <!-- Pasang konten di sini -->
    {% endblock body %}


        <!-- Footer -->
    <footer class="page-footer font-small pt-4 bottom">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase">D U E L</h5>
            <p>Website that helps you find your opponent and a place to play</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->

            <ul class="list-unstyled">
            <li>
                <a href="{% url 'base:home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'rekomendasi:rekomendasi' %}">Recommendation</a>
            </li>
            <li>
                <a href="{% url 'forum:forum' %}">Forum</a>
            </li>
            <li>
                <a href="#">FAQ</a>
            </li>
            <li>
                <a href="{% url 'team:team' %}">Our Team</a>
            </li>
            </ul>

        </div>
        <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: KD 10 Project
    </div>
    <!-- Copyright -->

    </footer>
    <!-- Footer -->

    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
    <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>
</body>


</html>